// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Components__CurrencyFieldController from "./components/currency_field_controller"
application.register("components--currency-field", Components__CurrencyFieldController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)
