version: "3.9"
services:
    db:
        container_name: postgres
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: pn_dev
            POSTGRES_PASSWORD: password
        volumes:
            - pg_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
volumes:
    pg_data:
